# pipelines/k8s/overlays/stg/configmap-patch.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-instance
data:
  dagster.yaml: |
    storage:
      postgres:
        postgres_db:
          hostname: { "env": "cloud_sql_postgres_host" }
          username: { "env": "cloud_sql_user" }
          password: { "env": "cloud_sql_password" }
          db_name: postgres
          port: 5432
          params:
            options: "-c search_path=dagster_instance_stg"