# pipelines/k8s/overlays/stg/run-launcher-patch.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-instance
data:
  dagster.yaml: |
    run_launcher:
      config:
        namespace: "dagster-stg"