version: 2

models:
  - name: top_100_forks
    columns:
      - name: project_title
        tests:
          - not_null
      - name: forks
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title]
  - name: top_100_stars
    columns:
      - name: project_title
        tests:
          - not_null
      - name: stars
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title]