version: 2

models:
  - name: top_50_projects
    columns:
      - name: project_title
        tests:
          - not_null
      - name: weighted_score
        tests:
          - not_null
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, latest_data_timestamp]
  - name: top_50_projects_trend
    columns:
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: report_date
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: project_title
        tests:
          - not_null
      - name: fork_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: stargaze_count  
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: contributor_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: commit_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: watcher_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: is_not_fork_ratio
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: commit_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: contributor_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: fork_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: stargaze_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: watcher_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: is_not_fork_ratio_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: weighted_score
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: project_rank
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: quartile_bucket
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: project_rank_category
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, report_date]