version: 2

models:
  - name: top_50_projects
    columns:
      - name: project_title
        tests:
          - not_null
      - name: weighted_score
        tests:
          - not_null
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, latest_data_timestamp]
  - name: top_50_projects_trend
    columns:
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: report_date
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: project_title
        tests:
          - not_null
      - name: repo_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: fork_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: stargaze_count  
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: contributor_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: commit_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: watcher_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: is_not_fork_ratio
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: commit_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: contributor_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: fork_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: stargaze_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: watcher_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: is_not_fork_ratio_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: weighted_score
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: project_rank
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: quartile_bucket
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: project_rank_category
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, report_date]
  - name: top_100_contributors
    columns:
      - name: contributor_login
        tests:
          - not_null
      - name: is_anon
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
      - name: dominant_language
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: location
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: contributor_unique_id_builder_love
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: contributor_html_url
        tests:
          - not_null
      - name: total_repos_contributed_to
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: total_contributions
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: contributions_to_og_repos
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: normalized_total_repo_quality_weighted_contribution_score_rank
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: followers_total_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: weighted_score_index
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: contributor_rank
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [contributor_unique_id_builder_love, latest_data_timestamp]
  - name: top_projects
    columns:
      - name: project_title
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: latest_data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: weighted_score_index
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: weighted_score_sma
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: contributor_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: contributor_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: repo_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: fork_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: fork_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: stargaze_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: stargaze_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: commit_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: commit_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: watcher_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: watcher_count_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: is_not_fork_ratio
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: is_not_fork_ratio_pct_change_over_4_weeks
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: project_rank
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: prior_4_weeks_project_rank
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: quartile_bucket
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: project_rank_category
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, latest_data_timestamp]
  - name: top_project_repos
    columns:
      - name: project_title
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: latest_data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: repo
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: fork_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: stargaze_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: watcher_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: weighted_score_index
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: repo_rank
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: quartile_bucket
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: repo_rank_category
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, repo, latest_data_timestamp]