version: 2

models:
  - name: top_100_projects_fork_count
    columns:
      - name: project_title
        tests:
          - not_null
      - name: fork_count
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title]
  - name: top_100_projects_stargaze_count
    columns:
      - name: project_title
        tests:
          - not_null
      - name: stargaze_count
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title]
  - name: top_50_projects_stargaze_trend
    columns:
      - name: project_title
        tests:
          - not_null
      - name: stargaze_count
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, latest_data_timestamp]
  - name: top_50_projects_fork_trend
    columns:
      - name: project_title
        tests:
          - not_null
      - name: fork_count
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, latest_data_timestamp]
  - name: top_50_projects_commit_trend
    columns:
      - name: project_title
        tests:
          - not_null
      - name: commit_count
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, latest_data_timestamp]
  - name: top_50_projects_contributor_trend
    columns:
      - name: project_title
        tests:
          - not_null
      - name: contributor_count
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, latest_data_timestamp]
  - name: top_50_projects
    columns:
      - name: project_title
        tests:
          - not_null
      - name: weighted_score
        tests:
          - not_null
      - name: latest_data_timestamp
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, latest_data_timestamp]
