# k8s/overlays/prod/daemon-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-daemon
spec:
  template:
    spec:
      containers:
      - name: dagster-daemon
        env:
        - name: DAGSTER_ENV
          value: "prod"
