# k8s/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Inherit all resources from the base
resources:
- ../../base
# Apply these patches
patches:
- path: webserver-patch.yaml
- path: daemon-patch.yaml