# k8s/overlays/prod/webserver-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-webserver
spec:
  template:
    spec:
      containers:
      - name: dagster-webserver
        env:
        - name: DAGSTER_ENV
          value: "prod"