dbt_pipelines:
  outputs:
    prod:
      dbname: "postgres"
      host: "{{ env_var('cloud_sql_postgres_host') }}"
      pass: "{{ env_var('cloud_sql_password')  }}"
      port: 5432
      schema: clean
      threads: 4
      type: "{{ env_var('cloud_sql_postgres_db')  }}"
      user: "{{ env_var('cloud_sql_user')  }}"
  target: prod
