steps:
- name: 'gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.15.1-alpine'
  id: 'Find-Proxy-Executable'
  entrypoint: 'sh'
  args: ['-c', 'find / -name cloud_sql_proxy']

options:
  logging: CLOUD_LOGGING_ONLY