availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/cloud_sql_user/versions/latest
    env: 'DB_USER'
  - versionName: projects/$PROJECT_ID/secrets/cloud_sql_password/versions/latest
    env: 'DB_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/cloud_sql_instance_connection_name/versions/latest
    env: 'INSTANCE_CONNECTION_NAME'
  - versionName: projects/$PROJECT_ID/secrets/gcp_project_id/versions/latest
    env: 'GCP_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/go_blockchain_ecosystem/versions/latest
    env: 'GH_PAT'
  - versionName: projects/$PROJECT_ID/secrets/bitbucket_api_key/versions/latest
    env: 'BB_KEY'

steps:
- name: 'bash'
  id: 'Create .env File'
  secretEnv:
  - 'DB_USER'
  - 'DB_PASSWORD'
  - 'INSTANCE_CONNECTION_NAME'
  - 'GCP_PROJECT_ID'
  - 'GH_PAT'
  - 'BB_KEY'
  env:
  - 'DAGSTER_ENV=stg'
  - 'DAGSTER_HOME=/opt/dagster/app'
  - 'DB_NAME=postgres'
  - 'DB_HOST=host.docker.internal'
  script: |
    echo "DAGSTER_ENV=$DAGSTER_ENV" > .env
    echo "DAGSTER_HOME=$DAGSTER_HOME" >> .env
    echo "cloud_sql_postgres_db=$DB_NAME" >> .env
    echo "cloud_sql_postgres_host=$DB_HOST" >> .env
    echo "cloud_sql_user=$$DB_USER" >> .env
    echo "cloud_sql_password=$$DB_PASSWORD" >> .env
    echo "cloud_sql_instance_connection_name=$$INSTANCE_CONNECTION_NAME" >> .env
    echo "gcp_project_id=$$GCP_PROJECT_ID" >> .env
    echo "go_blockchain_ecosystem=$$GH_PAT" >> .env
    echo "bitbucket_api_key=$$BB_KEY" >> .env

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--secret=id=env.list,src=.env',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dagster-repo/dagster-app:$SHORT_SHA',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dagster-repo/dagster-app:latest',
    './pipelines'
  ]

- name: 'us-central1-docker.pkg.dev/cloud-builders/docker/latest'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/dagster-repo/dagster-app']

- name: 'us-central1-docker.pkg.dev/cloud-builders/gke-deploy/latest'
  args:
  - 'run'
  - '--filename=pipelines/k8s/'
  - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/dagster-repo/dagster-app=us-central1-docker.pkg.dev/$PROJECT_ID/dagster-repo/dagster-app:$SHORT_SHA'
  - '--location=us-central1-c'
  - '--cluster=dagster-cluster'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/dagster-repo/dagster-app:$SHORT_SHA'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/dagster-repo/dagster-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY