availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/cloud_sql_instance_connection_name/versions/latest
    env: 'INSTANCE_CONNECTION_NAME'

steps:
- name: 'gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.15.1-alpine'
  id: 'Debug Proxy Startup'
  entrypoint: 'sh'
  args:
    - '-c'
    - '/cloud_sql_proxy --structured-logs --debug-logs $$INSTANCE_CONNECTION_NAME &'
  secretEnv: ['INSTANCE_CONNECTION_NAME']

options:
  logging: CLOUD_LOGGING_ONLY