# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-instance
data:
  # Paste the entire content of your updated dagster.yaml here
  dagster.yaml: |
    run_launcher:
        module: dagster_k8s
        class: K8sRunLauncher
        config:
            # Use the gke service account
            service_account_name: dagster-ksa
            # Point to the ConfigMap
            instance_config_map: dagster-instance
            # Point to the secret holding the DB password
            # get the file
            postgres_password_secret: cloudsql-db-credentials
            # use the key
            postgres_password_secret_key: password
            # This is true by default 
            load_incluster_config: true
            # Job image should match the one used by the daemon/webserver
            job_image: us-central1-docker.pkg.dev/data-pipelines-450611/dagster-repo/dagster-app:latest

            # Add env_vars for k8 to inject to job-specific containers
            env_vars:
                - name: cloud_sql_user
                    valueFrom:
                    secretKeyRef:
                        name: cloudsql-db-credentials
                        key: username
                - name: cloud_sql_password
                    valueFrom:
                    secretKeyRef:
                        name: cloudsql-db-credentials
                        key: password
                - name: cloud_sql_postgres_db
                    valueFrom:
                    secretKeyRef:
                        name: cloudsql-db-credentials
                        key: database
                - name: cloud_sql_postgres_host
                    value: "127.0.0.1"
                - name: GITHUB_API_TREBOR
                    valueFrom:
                    secretKeyRef:
                        name: github-api-secrets
                        key: github_finegrain_trebor
                - name: GITHUB_API_JACKATJ
                    valueFrom:
                    secretKeyRef:
                        name: github-api-secrets
                        key: github_finegrain_jackatj
                - name: BITBUCKET_API
                    valueFrom:
                    secretKeyRef:
                        name: bitbucket-api-secrets
                        key: bitbucket_api_key
                        
            # the k8 launcher also needs to spin up a cloud-sql-proxy sidecar
            pod_spec_config:
                containers:
                    - name: cloudsql-proxy
                    image: gcr.io/cloudsql-docker/gce-proxy:1.33.9
                    command:
                        - "/cloud_sql_proxy"
                        - "-instances=data-pipelines-450611:us-central1:builder-love=tcp:5432"
                    securityContext:
                        runAsNonRoot: true

        # This file configures the Dagster instance 
    run_coordinator:
        module: dagster.core.run_coordinator
        class: QueuedRunCoordinator
        config:
            max_concurrent_runs: 25
            tag_concurrency_limits:
            - key: "github_api_key1"
                value: "True"
                limit: 1
            - key: "github_api_key2"
                value: "True"
                limit: 1

    telemetry:
        enabled: false

    retention:
        schedule:
            purge_after_days: 180
        sensor:
            purge_after_days:
            skipped: 14
            failure: 45
            success: -1

    storage:
        postgres:
            postgres_db:
            hostname: { "env": "cloud_sql_postgres_host" }
            username: { "env": "cloud_sql_user" }
            password: { "env": "cloud_sql_password" }
            db_name: { "env": "cloud_sql_postgres_db" } 
            port: 5432