# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagster-webserver
  template:
    metadata:
      labels:
        app: dagster-webserver
    spec:
      serviceAccountName: dagster-ksa
      volumes:
      - name: dagster-instance-volume
        configMap:
          name: dagster-instance
      containers:
      # Your Dagster application container
      - name: dagster-webserver
        # The image will be dynamically set by Cloud Build
        image: us-central1-docker.pkg.dev/data-pipelines-450611/dagster-repo/dagster-app:latest
        command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: dagster-instance-volume
          mountPath: /opt/dagster/dagster_home/dagster.yaml
          subPath: dagster.yaml
        env:
        - name: cloud_sql_user
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: cloud_sql_user
        - name: cloud_sql_password
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: cloud_sql_password
        - name: cloud_sql_postgres_db
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: cloud_sql_postgres_db
        # This points to the sidecar proxy
        - name: cloud_sql_postgres_host
          value: "127.0.0.1"
        - name: DAGSTER_HOME
          value: "/opt/dagster/dagster_home"
        - name: DAGSTER_ENV
          value: "DAGSTER_ENV_PLACEHOLDER"
        # set the github api tokens
        - name: GITHUB_API_TREBOR
          valueFrom:
            secretKeyRef:
              name: github-api-secrets
              key: GITHUB_API_TREBOR
        - name: GITHUB_API_JACKATJ
          valueFrom:
            secretKeyRef:
              name: github-api-secrets
              key: GITHUB_API_JACKATJ
        - name: BITBUCKET_API
          valueFrom:
            secretKeyRef:
              name: bitbucket-api-secrets
              key: bitbucket_api_key

      # Cloud SQL Auth Proxy sidecar container
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.9
        command:
          - "/cloud_sql_proxy"
          - "-instances=data-pipelines-450611:us-central1:builder-love=tcp:5432" # Get this from your Cloud SQL instance page
        securityContext:
          runAsNonRoot: true