version: 2

models:
  - name: normalized_project_toml_files
    columns:
      - name: toml_file_data_url
        tests:
          - not_null
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [toml_file_data_url, data_timestamp]
  - name: normalized_project_organizations
    columns:
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
      - name: project_organization_url
        tests:
          - not_null
      - name: project_title
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_organization_url, project_title, data_timestamp]
  - name: normalized_project_sub_ecosystems
    columns:
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
      - name: project_title
        tests:
          - not_null
      - name: sub_ecosystem
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, sub_ecosystem, data_timestamp]
  - name: normalized_project_repos
    columns:
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
      - name: project_title
        tests:
          - not_null
      - name: repo
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, repo, data_timestamp]
  - name: normalized_project_repos_fork_count
    columns:
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
      - name: fork_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: repo
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [repo, data_timestamp]
  - name: normalized_project_repos_stargaze_count
    columns:
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
      - name: stargaze_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: repo
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [repo, data_timestamp]
  - name: normalized_project_repos_languages
    columns:
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
      - name: language_name
      - name: size
      - name: repo_languages_total_bytes
      - name: repo
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [repo, language_name, data_timestamp]
  - name: normalized_project_repos_commit_count
    columns:
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
      - name: commit_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: repo
        tests:
          - not_null
    tests:
      - unique_combination_of_columns:
          column_names: [repo, data_timestamp]
  - name: latest_project_toml_files
    columns:
      - name: toml_file_data_url
        tests:
          - not_null
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [toml_file_data_url, data_timestamp]
  - name: latest_project_organizations
    columns:
      - name: project_title
        tests:
          - not_null
      - name: project_organization_url
        tests:
          - not_null
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [project_organization_url, project_title, data_timestamp]
  - name: latest_project_sub_ecosystems
    columns:
      - name: project_title
        tests:
          - not_null
      - name: sub_ecosystem
        tests:
          - not_null
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, sub_ecosystem, data_timestamp]
  - name: latest_project_repos
    columns:
      - name: project_title
        tests:
          - not_null
      - name: repo
        tests:
          - not_null
      - name: repo_source
        tests:
          - not_null  
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [project_title, repo, data_timestamp]
  - name: latest_distinct_project_repos
    columns:
      - name: repo
        tests:
          - not_null
      - name: repo_source
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [repo, data_timestamp]
  - name: latest_active_distinct_project_repos
    columns:
      - name: repo
        tests:
          - not_null
      - name: is_active
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
      - name: repo_source
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [repo, data_timestamp]
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 350000
          max_value: 500000
  - name: latest_project_repos_commit_count
    columns:
      - name: repo
        tests:
          - not_null
      - name: commit_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [repo, data_timestamp]
  - name: latest_project_repos_fork_count
    columns:
      - name: repo
        tests:
          - not_null
      - name: fork_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [repo, data_timestamp]
  - name: latest_project_repos_stargaze_count
    columns:
      - name: repo
        tests:
          - not_null
      - name: stargaze_count
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [repo, data_timestamp]
  - name: latest_project_repos_languages
    columns:
      - name: repo
        tests:
          - not_null
      - name: language_name
      - name: size
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: repo_languages_total_bytes
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
      - name: data_timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp without time zone
    tests:
      - unique_combination_of_columns:
          column_names: [repo, language_name, data_timestamp]