version: 2

sources:
  - name: raw
    database: postgres
    schema: raw
    tables:
      - name: project_toml_files
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: project_organizations
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: project_sub_ecosystems
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: project_repos_stargaze_count
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: project_repos_fork_count
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: project_repos
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: project_repos_languages
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: project_repos_commit_count
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: latest_active_distinct_project_repos
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
  - name: clean
    database: postgres
    schema: clean
    tables:
      - name: normalized_project_toml_files
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: normalized_project_sub_ecosystems
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: normalized_project_organizations
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: normalized_project_repos
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: normalized_project_repos_fork_count
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: normalized_project_repos_stargaze_count
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: normalized_project_repos_languages
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: normalized_project_repos_commit_count
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: latest_active_distinct_project_repos
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: latest_distinct_project_repos
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: latest_project_organizations
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: latest_project_repos
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: latest_project_sub_ecosystems
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: latest_project_toml_files
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: latest_project_repos_commit_count
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: latest_project_repos_fork_count
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: latest_project_repos_languages
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 32, period: day}
      - name: latest_project_repos_stargaze_count
        loaded_at_field: data_timestamp
        freshness: 
          warn_after: {count: 8, period: day}
      - name: top_100_forks
      - name: top_100_stars
  - name: prod
    database: postgres
    schema: prod
    tables:
      - name: normalized_project_toml_files
      - name: normalized_project_sub_ecosystems
      - name: normalized_project_organizations
      - name: normalized_project_repos
      - name: normalized_project_repos_fork_count
      - name: normalized_project_repos_stargaze_count
      - name: normalized_project_repos_languages
      - name: normalized_project_repos_commit_count
      - name: latest_active_distinct_project_repos
      - name: latest_distinct_project_repos
      - name: latest_project_organizations
      - name: latest_project_repos
      - name: latest_project_sub_ecosystems
      - name: latest_project_toml_files
      - name: latest_project_repos_commit_count
      - name: latest_project_repos_fork_count
      - name: latest_project_repos_languages
      - name: latest_project_repos_stargaze_count
      - name: top_100_forks
      - name: top_100_stargaze